name: Build

on:
  push:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x.x"

      - name: Restore packages
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        
      - name: Test
        run: dotnet test


